# Generated by Django 2.1.2 on 2018-10-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopOneLawSimilarityName', models.TextField(max_length=100)),
                ('TopTwoLawSimilarityName', models.TextField(max_length=100)),
                ('TopThreeLawSimilarityName', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerList',
            fields=[
                ('LawyerName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('LawyerEvaluation', models.FloatField(default=0)),
                ('LawIntroducation', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UserPassword', models.CharField(max_length=100)),
                ('UserJob', models.CharField(max_length=50, null=True)),
                ('UserAvatar', models.FileField(upload_to='media')),
            ],
        ),
    ]
