# Generated by Django 2.1.2 on 2018-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawArticleList',
            fields=[
                ('Lawname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LawRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopOneLawRecommend', models.TextField(max_length=100)),
                ('TopTwoLawRecommend', models.TextField(max_length=100)),
                ('TopThreeLawRecommend', models.TextField(max_length=100)),
                ('TopFourLawRecommend', models.TextField(max_length=100)),
                ('TopFiveLawRecommend', models.TextField(max_length=100)),
                ('TopSixLawRecommend', models.TextField(max_length=100)),
                ('TopSevenLawRecommend', models.TextField(max_length=100)),
                ('TopeightLawRecommend', models.TextField(max_length=100)),
                ('TopNineLawRecommend', models.TextField(max_length=100)),
                ('TopTenLawRecommend', models.TextField(max_length=100)),
            ],
        ),
    ]
